name: Tests
on: [push]
jobs:
  tests:
    timeout-minutes: 220
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: yarn install
        run: yarn install

      - name: yarn test
        run: yarn test

      - name: yarn build:chronoblog
        run: yarn build:chronoblog

      - name: yarn build:chronoblog-netlify-cms
        run: yarn build:chronoblog-netlify-cms

      - name: yarn build:minimal
        run: yarn build:minimal

      - name: yarn build:tests
        run: yarn build:tests

      - name: yarn build:profile-minimal
        run: yarn build:profile-minimal

      - name: yarn build:profile
        run: yarn build:profile

      - name: yarn build:hacker
        run: yarn build:hacker
